<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TwoByOne" Id="{23b7d636-2f1d-460f-a2c1-62def41ab995}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK TwoByOne
VAR_INPUT
	
	START 				: BOOL; 
	STOP				: BOOL;

END_VAR
VAR_OUTPUT
	
Running					: BOOL;

END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="TwoByOne">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>