<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="AMP4330" Id="{b332215d-2169-486d-a2bd-2d78fe8264ff}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK AMP4330 
VAR_INPUT
END_VAR
VAR_OUTPUT
	
			MoverTypeWidth 				: 		LREAL := 77.5; // Mover Width/2 in mm
			MoverTypeLength				: 		LREAL := 77.5; // Mover Length/2 in mm 

END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="AMP4330">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>